### ISSUE TITLE
Can you provide the resnet18 pretrained models?

### ISSUE THREAD

**Issue by TuringKi** [HMRC-AEL/MonoDEVSNet#1]
just like the title.

**Comment by Akhil-Gurram** [comment]
Hi @TuringKi, 

Sorry, we didn't train monoDEVSNet on ResNet-18 to provide you a pretrained model, as we noticed a gap in results between ResNet and HRNet. [Paper Table. I](https://arxiv.org/pdf/2103.12209.pdf) 

Thank you,
