### ISSUE TITLE
About Training Instructions

### ISSUE THREAD

**Issue by underwang** [HMRC-AEL/MonoDEVSNet#2]
Hi, can you tell me the instructions for the best results? And how many epoch do you train for the best results.I have trained 44 epochs now, abs-rel =0.141, how many more epochs do I need.Thank you

**Comment by Akhil-Gurram** [comment]
Hi, 

The best results are achieved with these parameters.

python3 monodevsnet_trainer.py --png --use_dc --use_le --use_ms --version TheBestModel --models_fcn_name encoder HRNet --num_layers 48  --real_dataset kitti --syn_dataset vk_2.0 --real_data_path <path_to_real_dataset_folder> --syn_data_path <path_to_synthetic_dataset_folder> 

Besides, please use HRNet-W48-C as pretrained weights for training the MonoDEVSNet model
https://github.com/HRNet/HRNet-Image-Classification 

direct link to download the HRNet-W48-C ImageNet pretrained model: https://onedrive.live.com/?authkey=%21AKvqI6pBZlifgJk&cid=F7FD0B7F26543CEB&id=F7FD0B7F26543CEB%21116&parId=F7FD0B7F26543CEB%21105&action=locate

**Comment by underwang** [comment]
Thank you for your advice

**Comment by mitalbert** [comment]
Can you please explain how the arguments in options.py relate to the arguments in mono_dataset.py?

For example in monodepth2/options.py I see data_path, split and dataset parameters need to be passed. Are these used for validation? And if I understand correctly syn_data_path and real_data_path in mono_dataset.py are used for training the model and the domain classifier?
